#  Copyright 2026 Filippo Savi
#  Author: Filippo Savi <filssavi@gmail.com>
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Computes a fingerprint of the sources that define the on-disk data cache
# format and writes it into a header. The fingerprint is what versions the
# persistent cache: whenever any serialized data-model source changes the
# archive format may change, so the fingerprint changes and the cache is
# invalidated automatically. No manual version numbers are involved.
#
# Usage:
#   cmake -DSCHEMA_ROOT="<repository root>"
#         -DOUTPUT="<generated header path>"
#         -P hash_cache_schema.cmake

if(NOT DEFINED SCHEMA_ROOT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "hash_cache_schema.cmake requires SCHEMA_ROOT and OUTPUT")
endif()

file(GLOB_RECURSE SCHEMA_SOURCES
    "${SCHEMA_ROOT}/includes/data_model/*"
    "${SCHEMA_ROOT}/src/data_model/*"
)
list(SORT SCHEMA_SOURCES)

set(INPUT "")
foreach(f IN LISTS SCHEMA_SOURCES)
    file(READ "${f}" CONTENT)
    string(SHA256 CONTENT_HASH "${CONTENT}")
    string(APPEND INPUT "${f}:${CONTENT_HASH}\n")
endforeach()
string(SHA256 SCHEMA_HASH "${INPUT}")

file(WRITE "${OUTPUT}"
"// Generated by cmake/hash_cache_schema.cmake. Do not edit.\n"
"#ifndef ANANKE_CACHE_SCHEMA_HASH_HPP\n"
"#define ANANKE_CACHE_SCHEMA_HASH_HPP\n"
"\n"
"#define ANANKE_CACHE_SCHEMA_HASH \"${SCHEMA_HASH}\"\n"
"\n"
"#endif //ANANKE_CACHE_SCHEMA_HASH_HPP\n"
)

message(STATUS "Cache schema fingerprint: ${SCHEMA_HASH}")